---
<<<<<<< HEAD
=======
# tasks file for Percona
>>>>>>> 844e592f36f18a2b96a2cb74578e02c34fb213a7
- name: load os vars
  include_vars:
    file: "./vars/ubuntu.yaml"
    name: os

- name: create directory
  become: true
  file:
<<<<<<< HEAD
    path: "{{ os.xtradb_datadir }}"
=======
    path: "{{ os.dbdatadir }}"
>>>>>>> 844e592f36f18a2b96a2cb74578e02c34fb213a7
    state: directory

- name: stop service mysql
  service:
    name: mysql
    state: stopped
    enabled: yes

- name: copy existing datadir to new datadir
  copy:
    src: /var/lib/mysql
<<<<<<< HEAD
    dest: "{{ os.xtradb_datadir }}"
    remote_src: yes

    #- name: create user mysql
    #  become: true
    # user: 
    #name: mysql
    #group: mysql
    #uid: 1040
=======
    dest: "{{ os.dbdatadir }}"
    remote_src: yes

- name: create user mysql
  become: true
  user: 
    name: mysql
    group: mysql
    uid: 1040
>>>>>>> 844e592f36f18a2b96a2cb74578e02c34fb213a7

- name: change owner and group newdatadir
  shell: "{{ item }}"
  args:
    executable: /bin/bash
  with_items:
<<<<<<< HEAD
  - chown -R mysql:mysql "{{ os.xtradb_datadir }}"
  - chmod 750 "{{ os.xtradb_datadir }}"
=======
  - chown -R mysql:mysql "{{ os.dbdatadir }}"
  - chmod 750 "{{ os.dbdatadir }}"
>>>>>>> 844e592f36f18a2b96a2cb74578e02c34fb213a7

- name: change datadir in mysqld.cnf
  lineinfile:
    path: "{{ os.xtradb_confdir }}/mysqld.cnf"
    regexp: '^datadir'
<<<<<<< HEAD
    line: 'datadir = {{ os.xtradb_datadir }}'
=======
    line: 'datadir = {{ os.dbdatadir }}'
>>>>>>> 844e592f36f18a2b96a2cb74578e02c34fb213a7
    insertbefore: 'tmpdir*'
    owner: root
    group: root
    mode: 0644

- name: change datadir in apparmor
  lineinfile:
    path: /etc/apparmor.d/tunables/alias
    insertafter: 'alias*'
<<<<<<< HEAD
    line: 'alias /var/lib/mysql/ -> {{ os.xtradb_datadir }},'
=======
    line: 'alias /var/lib/mysql/ -> {{ os.dbdatadir }},'
>>>>>>> 844e592f36f18a2b96a2cb74578e02c34fb213a7
    state: present
    owner: root
    group: root
    mode: 0644

<<<<<<< HEAD
- name: restart apparmor
  service:
    name: apparmor
    state: reloaded
    enabled: yes
    force: true

- name: Check mysql directory if exist
=======
- name: check mysql directory if exist
>>>>>>> 844e592f36f18a2b96a2cb74578e02c34fb213a7
  stat:
    path: /var/lib/mysql.bak
  check_mode: yes
  register: check_directory

<<<<<<< HEAD
- name: Rename /var/lib/mysql
  command: mv /var/lib/mysql /var/lib/mysql.bak
  when: not check_directory.stat.exists
  notify:
   - Restart mysql  
=======
- name: rename directory /var/lib/mysql
  command: mv /var/lib/mysql /var/lib/mysql.bak
  when: not check_directory.stat.exist
  notify: 
    - Restart mysql 

- name: restart apparmor
  service:
    name: apparmor
    state: reloaded
    enabled: yes
    force: true
>>>>>>> 844e592f36f18a2b96a2cb74578e02c34fb213a7

- name: start percona mysql
  service:
    name: mysql
    state: started
<<<<<<< HEAD
    enabled: yes
=======
    enabled: yes
>>>>>>> 844e592f36f18a2b96a2cb74578e02c34fb213a7
