---
# tasks file for Percona
- name: load os vars
  include_vars:
    file: "./vars/ubuntu.yaml"
    name: os

- name: create directory
  become: true
  file:
    path: "{{ os.xtradb_datadir }}"
    state: directory

- name: stop service mysql
  service:
    name: mysql
    state: stopped
    enabled: yes

- name: copy existing datadir to new datadir
  shell: rsync -avz /var/lib/mysql "{{ os.xtradb_datadir }}"
  args:
    executable: /bin/bash
  #copy:
    #src: /var/lib/mysql
    #dest: "{{ os.xtradb_datadir }}"
    #remote_src: yes

    #- name: create user mysql
    #  become: true
    # user: 
    #name: mysql
    #group: mysql
    #uid: 1040

#- name: change owner and group newdatadir
#  shell: "{{ item }}"
#  args:
#    executable: /bin/bash
#  with_items:
#  - chown -R mysql:mysql "{{ os.xtradb_datadir }}"
#  - chmod 750 "{{ os.xtradb_datadir }}"

- name: change datadir in mysqld.cnf
  lineinfile:
    path: "{{ os.xtradb_confdir }}/mysqld.cnf"
    regexp: '^datadir'
    line: 'datadir = {{ os.xtradb_datadir }}/mysql'
    insertbefore: 'tmpdir*'
    owner: root
    group: root
    mode: 0644

- name: change datadir in apparmor
  lineinfile:
    path: /etc/apparmor.d/tunables/alias
    insertafter: 'alias*'
    line: 'alias /var/lib/mysql/ -> {{ os.xtradb_datadir }}/mysql/,'
    state: present
    owner: root
    group: root
    mode: 0644

- name: restart apparmor
  service:
    name: apparmor
    state: reloaded
    enabled: yes
    force: true

# - name: Check mysql directory if exist
#  stat:
#    path: /var/lib/mysql.bak
#  check_mode: yes
#  register: check_directory

- name: rename directory /var/lib/mysql
  shell: mv /var/lib/mysql /var/lib/mysql.bak
  args:
    executable: /bin/bash
  # when: not check_directory.stat.exist
  notify: 
    - Restart mysql 

- name: start bootstrap
  shell: /etc/init.d/mysql bootstrap-pxc
  args:
    executable: /bin/bash
