- name: load OS vars
  include_vars:
    file: "./vars/ubuntu.yaml"
    name: os

- name: get mysql password
  shell: grep "temporary password" /var/log/mysqld.log | awk '{print $11}'
  register: mysql_password

- name: set root init password if root password is null
  set_fact:
    root_password: "{{ percona.xtradb_root.password }}"
  when: mysql_password.stdout == ""

- name: set root init password if root password is not null null
  set_fact:
    root_password: "{{ mysql_password.stdout }}"
  when: mysql_password.stdout

- name: Update root password
  mysql_user: 
    name: root 
    host: "{{item}}" 
    password: "{{ percona.xtradb_root.password }}"
    login_user: "root"
    login_password: "{{ root_password }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  
- name: Delete anonymous MySQL user
  mysql_user: 
    name: "" 
    host: "{{item}}" 
    state: "absent" 
    login_user: "root"
    login_password: "{{ percona.xtradb_root.password }}"
  with_items:
    - localhost
    - "{{ ansible_nodename }}"

  # mysql_secure_installation
- name: Delete Hostname based MySQL user
  mysql_user: 
    name: root 
    host: "{{ ansible_nodename }}" 
    state: absent
    login_user: "root"
    login_password: "{{ percona.xtradb_root.password }}"

  # mysql_secure_installation
- name: Remove MySQL test database
  mysql_db: 
    name: test 
    state: absent 
    login_user: "root"
    login_password: "{{ percona.xtradb_root.password }}"



- name: mark if password changeed
  file:
    path:  "{{ os.xtradb_confdir }}/{{ percona.xtradb_preflight_lock.password_changed }}"
    owner: root
    group: root
    mode: '0600'
    state: touch
