- name: Deploy percona xtradb cluster on Ubuntu 1
  hosts: percona
  vars: 
    proxy:
      http_proxy: "{{ http_proxy | default('')}}"
      https_proxy: "{{ http_proxy | default('')}}"
      no_proxy: "{{ no_proxy | default('')}}"
    percona:
      xtradb_version: "57"
      xtradb_service: mysql
      xtradb_datadir: /var/lib/mysql
      xtradb_partition: /dev/sda1
      cluster_name: "percona-01"
      dbservicename: "percona"
      wsrep:
        binlog_format: ROW
        default_storage_engine: InnoDB
        wsrep_slave_threads: 8
        innodb_autoinc_lock_mode: 2
        pxc_strict_mode: DISABLED
        wsrep_auto_increment_control: false
        sst:
          username: sstuser
          password: sstpassword
      xtradb_preflight_lock:
        bootstraped: _bootstraped
        configured: _configured
        installed: _installed
        password_changed: _password_changed
        secured: _secured
      xtradb_root:
        username: root
        password: root
      mysql_options: |
        log_output=file
        slow_query_log=ON
        long_query_time=0
        max_connections=500
    xinetd:
      auth:
        user: lakilakibermain
        password: buayakecil
      resource_threshold: 75.0
  roles:
  - {role: percona}
  - {role: xinetd}
